# Generated by Django 5.0.1 on 2025-01-30 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OcApp', '0003_organrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organ_type', models.CharField(choices=[('Heart', 'Heart'), ('Lungs', 'Lungs'), ('Liver', 'Liver'), ('Kidneys', 'Kidneys'), ('Pancreas', 'Pancreas'), ('Corneas', 'Corneas')], max_length=50)),
                ('status', models.CharField(default='Available', max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_transplanted', models.DateTimeField(blank=True, null=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OcApp.donor')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='OcApp.organrequest')),
            ],
        ),
    ]
