# Generated by Django 5.0.1 on 2025-01-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OcApp', '0005_recipient_alter_organ_recipient_delete_organrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='organ',
            name='blood_type',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], default='---', max_length=3),
        ),
    ]
