# Generated by Django 5.1.5 on 2025-01-31 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OcApp', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
